sudo: required

language: cpp

notifications:
  email: false

env:
  global:
    - CELLMATE_PATH=/root/workspace/CellMate
    - DOCKER_IMAGE=kaifeichen/cellmate

services:
  - docker

script:
  - docker pull ${DOCKER_IMAGE}
  - docker run -v `pwd`:${CELLMATE_PATH} ${DOCKER_IMAGE} /bin/bash -c " cd ${CELLMATE_PATH}/script; chmod +x travis.sh; ./travis.sh "


