sudo: required

language: cpp

services:
  - docker

script:
  - docker pull kaifeichen/cellmate
  - docker run -v `pwd`:/root/CellMate_Server kaifeichen/cellmate /bin/sh -c "cd /root/CellMate_Server/build; cmake ..; make"
