sudo: required

language: cpp

notifications:
  email: false

env:
  global:
    - QT_PATH=/usr/local/Qt-5.9.1/bin
    - CELLMATE_PATH=/root/workspace/CellMate
    - DOCKER_IMAGE=kaifeichen/cellmate

services:
  - docker

script:
  - docker pull ${DOCKER_IMAGE}
  - docker run -v `pwd`:${CELLMATE_PATH} ${DOCKER_IMAGE} /bin/bash -c "PATH=${QT_PATH}:$PATH; cd ${CELLMATE_PATH}/script; chmod +x travis.sh; ./travis.sh "


