sudo: required

language: cpp

notifications:
  email: false

env:
  global:
    - QT_PATH=/usr/local/Qt-5.9.1/bin
    - SNAPLINK_PATH=/root/workspace/SnapLink
    - DOCKER_IMAGE=kaifeichen/snaplink

services:
  - docker

script:
  - docker pull ${DOCKER_IMAGE}
  - docker run -v `pwd`:${SNAPLINK_PATH} ${DOCKER_IMAGE} /bin/bash -c "PATH=${QT_PATH}:$PATH; cd ${SNAPLINK_PATH}/script; chmod +x travis.sh; ./travis.sh "


